language: julia
dist: trusty
julia:
  - 1.0
  - 1.1
  - 1.2
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'include("install.jl"); include("runtests.jl")'
